const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slimfit Shirts',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:750,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
           _id:'2',
           name:'PE FormalShirt',
           category:'Shirts',
           image:'/images/p2.jpg',
           price:899,
           brand: 'PE',
           rating: 4.0,
           numReviews: 10,
           description: 'high quality product',
       },
       {
        _id:'3',
       name:'AlenSoly Shirts',
       category:'Shirts',
       image:'/images/p3.jpg',
       price:1499,
       brand: 'AlenSoly',
       rating: 4.8,
       numReviews: 17,
       description: 'high quality product',
    },
    {
        _id:'4',
       name:'DE Formal Pants',
       category:'Pants',
       image:'/images/p4.jpg',
       price:999,
       brand: 'DE',
       rating: 4.5,
       numReviews: 14,
       description: 'high quality product',
    },
    {
        _id:'5',
       name:'Denim SlimFit Pants',
       category:'Pants',
       image:'/images/p5.jpg',
       price:1599,
       brand: 'Denim',
       rating: 4.5,
       numReviews: 10,
       description: 'high quality product',
    },
    {
        _id:'6',
       name:'PA Slimfit Pants',
       category:'Pants',
       image:'/images/p6.jpg',
       price:2199,
       brand: 'PA',
       rating: 4.5,
       numReviews: 15,
       description: 'high quality product',
        },
    ],
};
export default data;